# Generated by Django 5.2.8 on 2025-11-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=50)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discountType', models.CharField(max_length=20)),
                ('discountValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maxDiscountAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('usageLimitPerUser', models.IntegerField(blank=True, null=True)),
                ('eligibility', models.CharField(blank=True, max_length=100)),
                ('uuid', models.UUIDField(editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userTier', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('lifetimeSpend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordersPlaced', models.IntegerField()),
            ],
        ),
    ]
